apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: db-deployment
  name: db-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db-vdt2023
  template:
    metadata:
      labels:
        app: db-vdt2023
    spec:
      containers:
      - name: db-container
        image: mysql:8.0
        ports:
        - containerPort: 3306