apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-dev
  name: nginx-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
        - image: nginx
          name: nginx-dev
          resources:
           limits:
             memory: "100Mi"
             cpu: "200m"
          ports:
            - containerPort: 8088