- name: Create fluentd directory
  file:
    path: var/Fluent-Docker/fluentd/conf
    state: directory

- name: Create docker-compose file
  copy:
    src: ../templates/docker-compose.yml
    dest: var/Fluent-Docker/docker-compose.yaml

- name: Copy Dockerfile
  copy:
    src: ../templates/Dockerfile
    dest: var/Fluent-Docker/fluentd/Dockerfile

- name: Copy fluentd.conf
  copy:
    src: ../templates/fluentd.conf
    dest: ./fluentd/conf/fluentd.conf

- name: Build and run fluentd container
  command: docker compose up -d
  args:
    chdir: var/Fluent-Docker/