- name: Pull backend-vdt2023 Docker image - always pull v1.0.5 version every playbook executes
  command: docker pull duogglong/backend-vdt2023:v1.0.5 

- name: Run Docker container backend-vdt2023
  docker_container:
    name: "{{ backend_container_name }}"
    image: duogglong/backend-vdt2023:v1.0.5
    state: started
    interactive: true
    tty: true
    ports:
      - "8088:8088"
    networks:
      - name: "{{ network_name }}"
