name: Java Test Main

on:
  pull_request:
    branches:
      - mainvdt

defaults:
  run:
    working-directory: ./10.GK/backend-vdt2023   

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  build-and-push-image:
    needs: build-and-test  # Công việc "build-and-push-image" phụ thuộc vào công việc "build-and-test"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get commit SHA
      id: commit_sha
      run: echo "::set-output name=SHA::$(git rev-parse --short HEAD)"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: 10.GK/backend-vdt2023
        push: true
        tags: duogglong/backend-vdt2023:${{ steps.commit_sha.outputs.SHA }}